void main(){
  String sehir = "Kayseri";
  String ulke = "Türkiye";
  String odeme_tarihi = "11.11.2022";
  double odeme = 11.2;
  int siparis_adeti = 5;
  String araba_modeli = "Toyota";
  String kitap_adi = "Kinyas ve Kayra";
  String yayinlama_tarihi = "12.09.1998";
  String telefon = "05428734859";
  int posta_kodu = 38023;
  String email = "mail@mail.com";
  String meslek = "Mühendis";
  int stok_miktari = 12;
  String musteri_adi = "Ahmet";
  double bakiye = 97.23;
  String urun_adi = "Bilgisayar";
  double yemek_fiyati = 12.50;
  String marka = "Dell";
  String muzik_adi = "Angelica";
  String video_suresi = "12:22";
  double urun_puani = 4.6;
  String resim_adi = "resim.jpg";
  String dosya_formati = "mp4";
  String renk = "mavi";
  String otobus_hatti = "500T";
  int kalan_dakika = 12;
  int takip_kodu = 542541;
  int kupon_suresi = 12;
  String renk_kodu = "FFFFFF";
  String telefon_modeli = "iPhone";
  double ekran_boyutu = 14.1;
  String kupon_kodu = "JI2DJ2S";
  double agirlik = 21.3;
  String ulusal_gun = "23 Nisan";
  String tatil_gunu = "Cumartesi";
  String rezervasyon_tarihi = "11.11.22";
  String sokak_adi = "Atatürk";
  String fatura_adresi = "İstanbul";

  print(sehir);
  print(ulke);
  print(odeme_tarihi);
  print(odeme);
  print(siparis_adeti);
  print(araba_modeli);
  print(kitap_adi);
  print(yayinlama_tarihi);
  print(telefon);
  print(posta_kodu);
  print(email);
  print(meslek);
  print(stok_miktari);
  print(musteri_adi);
  print(bakiye);
  print(urun_adi);
  print(yemek_fiyati);
  print(marka);
  print(muzik_adi);
  print(video_suresi);
  print(urun_puani);
  print(resim_adi);
  print(dosya_formati);
  print(renk);
  print(otobus_hatti);
  print(kalan_dakika);
  print(takip_kodu);
  print(kupon_suresi);
  print(renk_kodu);
  print(telefon_modeli);
  print(ekran_boyutu);
  print(kupon_kodu);
  print(agirlik);
  print(ulusal_gun);
  print(tatil_gunu);
  print(rezervasyon_tarihi);
  print(sokak_adi);
  print(fatura_adresi);
}